run task:
    # Direct compiler output to stderr so only the program output shows up in stdout for the AoC runner to capture.
    @agda --compile-dir=bin/ --compile a{{task}}.agda 1>&2
    @./bin/a{{task}}

exists task:
    #!/bin/sh
    if [ ! -f a{{task}}.agda ]; then
        exit 1
    fi

clean:
    rm -rf *.agdai bin/
