[package]
name = "aoc-rust"
version = "0.1.0"
authors = ["rsaarelm <risto.saarelma@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "2010"
path = "src/2010.rs"

[dependencies]
