[package]
name = "aoc-rust"
version = "0.1.0"
authors = ["rsaarelm <risto.saarelma@iki.fi>"]
edition = "2018"

[lib]
name = "aoc"

[dependencies]
glam = "0.20"
itertools = "0.10"
lazy_static = "1"
memoize = "0.1"
nom = "7"
rand = "0.8"
rayon = "1"
regex = "1"
