run task:
    #!/bin/sh
    if [[ -z "${TURBO}" ]]; then
        >&2 echo "Running Rust solution in debug mode, set TURBO=1 to go fast."
        RUST_BACKTRACE=1 cargo run --example {{task}}
    else
        RUST_BACKTRACE=1 cargo run --release --example {{task}}
    fi

exists task:
    #!/bin/sh
    if [ ! -f examples/{{task}}.rs ]; then
        exit 1
    fi

test:
    cargo test
    cargo test --examples
