run task:
    #!/bin/sh
    if [[ -z "${DEBUG}" ]]; then
        RUST_BACKTRACE=1 cargo run --release --example {{task}}
    else
        RUST_BACKTRACE=1 cargo run --example {{task}}
    fi

exists task:
    #!/bin/sh
    if [ ! -f examples/{{task}}.rs ]; then
        exit 1
    fi

test:
    cargo test
    cargo test --examples
